config/routes.rb
Rails.application.routes.draw do
  get '/courses/all', to: 'courses#all'
  resources :courses
  resources :subjects
  resources :instructors
  get 'sessions/new'
  post 'enrollments/create/:user_id&:course_id', to: 'enrollments#create'
  resources :users
  get 'users/new'
  root 'home_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup/', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments
  has_many :users, :through => :enrollments
  has_many :course_subject_links
  has_many :subjects, :through => :course_subject_links
end

app/models/course_subject_link.rb
class CourseSubjectLink < ApplicationRecord
  belongs_to :course
  belongs_to :subject
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :course_subject_links
  has_many :courses, :through => :course_subject_links
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :enrollments
  has_many :courses, :through => :enrollments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    if params[:search] && params[:subject]
      @courses = Course.joins(:course_subject_links).where("LOWER(courses.name) LIKE ? and course_subject_links.subject_id = ?", "%#{params[:search].downcase}%", params[:subject])
    elsif params[:subject]
      @courses = Course.joins(:course_subject_links).where("course_subject_links.subject_id = ?", params[:subject])
    else
      @courses = Course.all
    end
  end


  def all
    @courses = Course.all
  end

  def add_course
    user = User.find(params[:user_id])
    course = Course.find(params[:course_id])
    Enrollment.create(user_id:user.id, course_id:course.id)
    redirect_to user
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:term, :code, :name, :description, :credits, :independent_study)
    end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:term, :name, :abbreviation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

    private

      def user_params
        params.require(:user).permit(:name, :email, :password,
                             :password_confirmation)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/courses/_courses.html.erb
<% if @courses.blank? %>
  <h4>There are no courses containing the term <%= params[:search] %>.</h4>
<% elsif logged_in? %>
  <% @courses = @courses - current_user.courses %>
  <table>
    <thead>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Description</th>
        <th>Independent study</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.code %></td>
          <td><%= course.name %></td>
          <td><%= course.description %></td>
          <td><%= course.independent_study %></td>
          <td><%= link_to 'Show', course %></td>
          <% if logged_in? %>
              <td><%= form_for(:enrollment, url: "/enrollments/create/#{current_user.id}&#{course.id}") do |f| %>
                    <%= f.submit "Enroll"%>
                  <% end %>
              </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>Please log in to see courses.</h2>
<% end %>

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term %>
    <%= f.number_field :term %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :credits %>
    <%= f.number_field :credits %>
  </div>

  <div class="field">
    <%= f.label :independent_study %>
    <%= f.check_box :independent_study %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/all.html.erb
<h1>All Courses</h1>
<%= render 'courses' %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>
<h2>Search</h2>
<%= form_tag(courses_path, method: "get", id: "search", remote: true) do %>
  <%= select_tag "subject", options_from_collection_for_select(Subject.all, "id", "name"), id: "subjects" %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Courses" %>
<% end %>

<div id="courses">
  <%= render 'courses' %>
</div>

app/views/courses/index.js.erb
$("#courses").html("<%= escape_javascript(render("courses")) %>")

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term:</strong>
  <%= @course.term %>
</p>

<p>
  <strong>Code:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Credits:</strong>
  <%= @course.credits %>
</p>

<p>
  <strong>Independent study:</strong>
  <%= @course.independent_study %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/home_pages/home.html.erb
<h1>Home</h1>

  <float><h2><%= link_to "Sign in", login_path %></h2></float>
  <float><h2><%= link_to "Sign up", signup_path %></h2></float>

app/views/search/search.html.erb
<h1>Search</h1>
<p> THIS IS NOW DEPRECATED. I AM LEAVING IT IN FOR REFERENCE PURPOSES, BUT THIS PAGE IS NO LONGER USED.
  TO PERFORM SEARCHES WITH AJAX FUNCTIONALITY, USE /courses. THANK YOU</p>
<%= form_tag(courses_path, :method => "get", id: "search") do %>
  <%= select_tag "subject", options_from_collection_for_select(Subject.all, "id", "name") %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Courses" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>